# Generated by Django 3.1.5 on 2021-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
