# Generated by Django 3.1.5 on 2021-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210212_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('artist_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sold', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('PA', 'Painting'), ('DR', 'Drawing'), ('CE', 'Ceramics'), ('SC', 'Sculpture'), ('PR', 'Prints'), ('CA', 'Cards'), ('BO', 'Books'), ('MX', 'Mixed')], default='PA', max_length=2)),
                ('created_at', models.DateTimeField()),
                ('image_path', models.URLField(blank=True, max_length=1024, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
